/* 
 * 路由表对象：
 * 该文件挂载在Vue原型中 $mRoutesConfig
 * 作用：调用$mRouter对象的方法 传入以下对应的路由对象，详细见common目录下的router.js
 * 示例：this.$mRouter.push({route:this.$mRoutesConfig.main,query:{a:1}})
 * 注意：所有在pages目录下新建的页面都必须在"路由表"中进行声明，并且在框架的pages.json注册。
 * 
 * 配置参数项说明： 
 * name:可选配置 （路由名称）
 * path:必填配置 （路由地址）
 * requiresAuth:可选配置 （是否权限路由）
 */
export default {
	role:{
		name:'选择注册角色',
		path:'/pages/register/role',
		requiresAuth:false
	},
	register:{
		name:'注册',
		path:'/pages/register/register',
		requiresAuth:false
	},
	login:{
		name:'登录',
		path:'/pages/login/login',
		requiresAuth:false
	},
	richText:{
		name:'协议 须知 之类',
		path:'/pages/common/richText',
		requiresAuth:false
	},
	
	index:{
		name:'首页',
		path:'/pages/index/index',
		requiresAuth:true
	},
	goodsDetail:{
		name:'商品详情',
		path:'/pages/index/goodsDetail',
		requiresAuth:true
	},
	submitOrder:{
		name:'提交订单',
		path:'/pages/index/submitOrder',
		requiresAuth:true
	},
	payOrder:{
		name:'支付',
		path:'/pages/index/payOrder',
		requiresAuth:true
	},
	cateGoods:{
		name:'分类商品列表',
		path:'/pages/category/cateGoods',
		requiresAuth:true
	},
	category:{
		name:'全部分类',
		path:'/pages/category/category',
		requiresAuth:true
	},
	sign:{
		name:'签到',
		path:'/pages/sign/sign',
		requiresAuth:true
	},
	lottery:{
		name:'抽奖',
		path:'/pages/sign/lottery',
		requiresAuth:true
	},
	lotteryRecord:{
		name:'中奖记录',
		path:'/pages/sign/lotteryRecord',
		requiresAuth:true
	},

	
	recommend:{
		name:'推荐',
		path:'/pages/index/recommend',
		requiresAuth:true
	},
	query:{
		name:'参军服务咨询',
		path:'/pages/query/query',
		requiresAuth:true
	},
	doQuery:{
		name:'参军服务咨询',
		path:'/pages/query/doQuery',
		requiresAuth:true
	},
	queryRecord:{
		name:'咨询记录',
		path:'/pages/query/queryRecord',
		requiresAuth:true
	},
	soldierZone:{
		name:'军人专区',
		path:'/pages/index/soldierZone',
		requiresAuth:true
	},
	
	froum:{
		name:'论坛',
		path:'/pages/froum/froum',
		requiresAuth:true
	},
	froumDetail:{
		name:'兵站论坛帖子详情',
		path:'/pages/froum/froumDetail',
		requiresAuth:true
	},
	publish:{
		name:'兵站论坛 发表帖子',
		path:'/pages/froum/publish',
		requiresAuth:true
	},
	doComment:{
		name:'回复',
		path:'/pages/froum/doComment',
		requiresAuth:true
	},
	
	citys:{
		name:'城市站',
		path:'/pages/citys/citys',
		requiresAuth:true
	},
	shopDetail:{
		name:'店铺详情',
		path:'/pages/citys/shopDetail',
		requiresAuth:true
	},
	cart:{
		name:'购物车',
		path:'/pages/cart/cart',
		requiresAuth:true
	},
	
	mine:{
		name:'我的',
		path:'/pages/mine/mine',
		requiresAuth:true
	},
	order:{
		name:'我的订单',
		path:'/pages/mine/order',
		requiresAuth:true
	},
	orderDetail:{
		name:'订单详情',
		path:'/pages/mine/orderDetail',
		requiresAuth:true
	},
	personInfo:{
		name:'个人信息',
		path:'/pages/mine/personInfo',
		requiresAuth:true
	},
	message:{
		name:'消息',
		path:'/pages/mine/message',
		requiresAuth:true
	},
	setting:{
		name:'设置',
		path:'/pages/setting/setting',
		requiresAuth:true
	},
	address:{
		name:'收货地址',
		path:'/pages/setting/address/address',
		requiresAuth:true
	},
	updateAddr:{
		name:'收货地址',
		path:'/pages/setting/address/updateAddr',
		requiresAuth:true
	},
	feedback:{
		name:'意见反馈',
		path:'/pages/setting/feedback',
		requiresAuth:true
	},
	password:{
		name:'支付密码',
		path:'/pages/setting/password',
		requiresAuth:true
	},
	savePwd:{
		name:'支付密码',
		path:'/pages/setting/savePwd',
		requiresAuth:true
	},
	collection:{
		name:'我的收藏',
		path:'/pages/mine/collection',
		requiresAuth:true
	},
	points:{
		name:'我的积分',
		path:'/pages/mine/points',
		requiresAuth:true
	},
	wallet:{
		name:'我的钱包',
		path:'/pages/mine/wallet/wallet',
		requiresAuth:true
	},
	rechange:{
		name:'充值',
		path:'/pages/mine/wallet/rechange',
		requiresAuth:true
	},
	cashout:{
		name:'提现',
		path:'/pages/mine/wallet/cashout',
		requiresAuth:true
	},
	cashRecd:{
		name:'提现记录',
		path:'/pages/mine/wallet/cashRecd',
		requiresAuth:true
	},
	aliInfo:{
		name:'提现 支付宝信息',
		path:'/pages/mine/wallet/aliInfo',
		requiresAuth:true
	},
	coupons:{
		name:'优惠券',
		path:'/pages/mine/coupons',
		requiresAuth:true
	},
	
}